# Generated by Django 5.2.6 on 2025-10-22 14:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0026_alter_formpage_body_alter_gallerypage_body_and_more"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaRenditionPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [("media", 0)],
                        blank=True,
                        block_lookup={
                            0: (
                                "bakerydemo.base.blocks.TestMediaBlock",
                                (),
                                {"icon": "media"},
                            )
                        },
                        verbose_name="Home content block",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
