# Generated by Django 5.2.6 on 2025-10-23 12:34

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0027_mediarenditionpage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediarenditionpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("media", 0), ("media_rendition", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "bakerydemo.base.blocks.TestMediaBlock",
                        (),
                        {"allow_renditions": False, "icon": "media"},
                    ),
                    1: ("bakerydemo.base.blocks.TestMediaBlock", (), {"icon": "media"}),
                },
                verbose_name="Content block",
            ),
        ),
    ]
